import type { Review, MovieList } from "./types"

export const reviews: Review[] = [
  {
    id: "1",
    slug: "the-shawshank-redemption",
    title: "The Shawshank Redemption",
    year: 1994,
    genres: ["Drama"],
    imageUrl: "/movies/the_shawshank_redemption.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2023-05-15",
    fullReview: "A timeless classic that explores the human spirit...",
    isTopFilm: true,
  },
  {
    id: "2",
    slug: "inception",
    title: "Inception",
    year: 2010,
    genres: ["Action", "Sci-Fi", "Thriller"],
    imageUrl: "/movies/inception.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2023-06-20",
    fullReview: "A mind-bending journey through dreams within dreams...",
    isTopFilm: false,
  },
  {
    id: "3",
    slug: "the-godfather",
    title: "The Godfather",
    year: 1972,
    genres: ["Drama", "Crime"],
    imageUrl: "/movies/the_godfather.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2023-04-10",
    fullReview: "An epic tale of family, power, and the American dream...",
    isTopFilm: true,
  },
  {
    id: "4",
    slug: "pulp-fiction",
    title: "Pulp Fiction",
    year: 1994,
    genres: ["Drama", "Crime"],
    imageUrl: "/movies/pulp_fiction.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2023-07-05",
    fullReview: "A groundbreaking masterpiece of nonlinear storytelling...",
    isTopFilm: true,
  },
  {
    id: "5",
    slug: "the-dark-knight",
    title: "The Dark Knight",
    year: 2008,
    genres: ["Action", "Crime", "Drama"],
    imageUrl: "/movies/the_dark_knight.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2023-03-18",
    fullReview: "A gripping superhero epic that transcends its genre...",
    isTopFilm: false,
  },
  {
    id: "6",
    slug: "the-matrix",
    title: "The Matrix",
    year: 1999,
    genres: ["Action", "Sci-Fi"],
    imageUrl: "/movies/the_matrix.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2023-09-10",
    fullReview: "A groundbreaking science fiction action film that explores the nature of reality. The Matrix's innovative special effects and philosophical themes have made it a cultural phenomenon, sparking countless discussions about simulation theory and the nature of free will.  The action sequences are still breathtaking, and the story continues to resonate with audiences today.  It's a must-see for any fan of the genre.",
    isTopFilm: false,
  },
  {
    id: "7",
    slug: "forrest-gump",
    title: "Forrest Gump",
    year: 1994,
    genres: ["Drama", "Romance"],
    imageUrl: "/movies/forrest_gump.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2023-10-25",
    fullReview: "A heartwarming and poignant story about a simple man who lives an extraordinary life. Forrest Gump's journey through American history is both comedic and tragic, offering a unique perspective on the major events of the 20th century.  Tom Hanks delivers a career-defining performance, and the film's soundtrack is simply iconic. While some may find it sentimental, its emotional impact is undeniable.",
    isTopFilm: false,
  },
  {
    id: "8",
    slug: "schindlers-list",
    title: "Schindler's List",
    year: 1993,
    genres: ["Biography", "Drama", "History"],
    imageUrl: "/movies/schindlers_list.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2023-11-05",
    fullReview: "A powerful and harrowing film about the Holocaust. Schindler's List tells the true story of Oskar Schindler, a German businessman who saved the lives of hundreds of Jews during World War II.  Liam Neeson's performance is masterful, and Steven Spielberg's direction is both sensitive and unflinching.  This film is a testament to the resilience of the human spirit in the face of unimaginable horror, and a reminder of the importance of remembering history.",
    isTopFilm: false,
  },
  {
    id: "9",
    slug: "goodfellas",
    title: "Goodfellas",
    year: 1990,
    genres: ["Crime", "Drama"],
    imageUrl: "/movies/goodfellas.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2023-12-12",
    fullReview: "A classic gangster film that explores the rise and fall of a group of mob associates. Goodfellas is a fast-paced and violent film, but it's also a brilliantly crafted character study.  Robert De Niro, Ray Liotta, and Joe Pesci deliver unforgettable performances.  Martin Scorsese's direction is energetic and stylish, making this one of the most influential films of the genre.",
    isTopFilm: false,
  },
  {
    id: "10",
    slug: "the-silence-of-the-lambs",
    title: "The Silence of the Lambs",
    year: 1991,
    genres: ["Crime", "Drama", "Thriller"],
    imageUrl: "/movies/the_silence_of_the_lambs.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-01-19",
    fullReview: "A chilling and suspenseful thriller that pits a young FBI trainee against a brilliant but insane cannibalistic serial killer. The Silence of the Lambs is a masterclass in suspense, with unforgettable performances from Jodie Foster and Anthony Hopkins.  The film's psychological depth and disturbing imagery have made it a landmark of the genre, and it continues to captivate audiences today.",
    isTopFilm: false,
  },
  {
    id: "11",
    slug: "saving-private-ryan",
    title: "Saving Private Ryan",
    year: 1998,
    genres: ["Drama", "War"],
    imageUrl: "/movies/saving_private_ryan.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2024-02-22",
    fullReview: "A realistic and brutal depiction of the D-Day landings and the subsequent battle for Normandy. Saving Private Ryan is a powerful anti-war film that doesn't shy away from the horrors of combat.  The film's opening sequence is particularly harrowing, and the performances from Tom Hanks and the rest of the cast are superb.  While the film's patriotism has been debated, its impact on the war film genre is undeniable.",
    isTopFilm: false,
  },
  {
    id: "12",
    slug: "gladiator",
    title: "Gladiator",
    year: 2000,
    genres: ["Action", "Adventure", "Drama"],
    imageUrl: "/movies/gladiator.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2024-03-08",
    fullReview: "A sweeping historical epic about a Roman general who is betrayed and forced into slavery. Gladiator is a visually stunning film with thrilling action sequences and a compelling story of revenge. Russell Crowe delivers a powerful performance as Maximus, and the film's soundtrack is both epic and moving. While historical inaccuracies have been noted, Gladiator's entertainment value is undeniable.",
    isTopFilm: false,
  },
  {
    id: "13",
    slug: "lord-of-the-rings-the-fellowship-of-the-ring",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    genres: ["Adventure", "Fantasy"],
    imageUrl: "/movies/lord_of_the_rings_the_fellowship_of_the_ring.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-04-15",
    fullReview: "The first installment in Peter Jackson's epic trilogy, The Fellowship of the Ring introduces audiences to the magical world of Middle-earth and the quest to destroy the One Ring.  The film's visual effects are stunning, and the cast delivers exceptional performances.  The story is both exciting and emotionally resonant, making this a landmark achievement in fantasy filmmaking.  It's a must-see for any fan of the genre.",
    isTopFilm: false,
  },
  {
    id: "14",
    slug: "the-departed",
    title: "The Departed",
    year: 2006,
    genres: ["Crime", "Drama", "Thriller"],
    imageUrl: "/movies/the_departed.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-05-22",
    fullReview: "A gripping crime thriller about an undercover cop and a mole within the Boston Irish Mob. The Departed is a complex and suspenseful film with brilliant performances from Leonardo DiCaprio, Matt Damon, and Jack Nicholson. Martin Scorsese's direction is sharp and stylish, and the film's twists and turns will keep you on the edge of your seat. It's a modern classic of the genre.",
    isTopFilm: false,
  },
  {
    id: "15",
    slug: "no-country-for-old-men",
    title: "No Country for Old Men",
    year: 2007,
    genres: ["Crime", "Drama", "Thriller"],
    imageUrl: "/movies/no_country_for_old_men.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-06-29",
    fullReview: "A dark and suspenseful thriller about a hunter who stumbles upon a bag of money and finds himself pursued by a relentless killer. No Country for Old Men is a masterclass in suspense, with a chilling performance from Javier Bardem as the iconic Anton Chigurh. The Coen brothers direction is masterful, and the film's bleak and atmospheric tone is perfectly suited to the source material. It's a must-see for fans of the genre.",
    isTopFilm: false,
  },
  {
    id: "16",
    slug: "there-will-be-blood",
    title: "There Will Be Blood",
    year: 2007,
    genres: ["Drama"],
    imageUrl: "/movies/there_will_be_blood.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-07-06",
    fullReview: "A powerful and unsettling drama about a ruthless oil prospector in the early 20th century. There Will Be Blood is a character study of ambition, greed, and the corrupting influence of power. Daniel Day-Lewis delivers a tour-de-force performance as Daniel Plainview, and Paul Thomas Anderson's direction is both visually stunning and emotionally resonant. The film's ending is both shocking and unforgettable, leaving a lasting impression on the viewer.",
    isTopFilm: false,
  },
  {
    id: "17",
    slug: "the-social-network",
    title: "The Social Network",
    year: 2010,
    genres: ["Biography", "Drama"],
    imageUrl: "/movies/the_social_network.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2024-08-13",
    fullReview: "A compelling drama about the creation of Facebook and the complex relationships between its founders. The Social Network is a timely and relevant film that explores themes of ambition, betrayal, and the impact of technology on our lives. Jesse Eisenberg delivers a nuanced performance as Mark Zuckerberg, and David Fincher's direction is sharp and stylish. The film's dialogue is witty and insightful, making it a must-see for anyone interested in the digital age.",
    isTopFilm: false,
  },
  {
    id: "18",
    slug: "whiplash",
    title: "Whiplash",
    year: 2014,
    genres: ["Drama", "Music"],
    imageUrl: "/movies/whiplash.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2024-09-20",
    fullReview: "An intense and thrilling drama about a young drummer who pushes himself to his limits under the tutelage of a demanding and abusive instructor. Whiplash is a film that will leave you breathless, with stunning performances from Miles Teller and J.K. Simmons. The film's exploration of ambition, perfectionism, and the cost of greatness is both compelling and disturbing. The drumming sequences are electrifying, making this a must-see for any music lover.",
    isTopFilm: false,
  },
  {
    id: "19",
    slug: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: 2015,
    genres: ["Action", "Adventure", "Sci-Fi"],
    imageUrl: "/movies/mad_max_fury_road.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-10-27",
    fullReview: "A visually stunning and action-packed film set in a post-apocalyptic wasteland. Mad Max: Fury Road is a masterclass in visual storytelling, with breathtaking stunts and practical effects. Charlize Theron delivers a powerful performance as Furiosa, and Tom Hardy is equally compelling as Max Rockatansky. The film's relentless pace and innovative action sequences make it a must-see for any fan of the genre.",
    isTopFilm: false,
  },
  {
    id: "20",
    slug: "moonlight",
    title: "Moonlight",
    year: 2016,
    genres: ["Drama"],
    imageUrl: "/movies/moonlight.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-11-03",
    fullReview: "A beautiful and moving coming-of-age story about a young man growing up in Miami. Moonlight is a film that explores themes of identity, masculinity, and the search for belonging. The film's poetic imagery and sensitive performances make it a truly unforgettable experience. It's a must-see for anyone who appreciates thoughtful and emotionally resonant cinema.",
    isTopFilm: false,
  },
  {
    id: "21",
    slug: "parasite",
    title: "Parasite",
    year: 2019,
    genres: ["Comedy", "Drama", "Thriller"],
    imageUrl: "/movies/parasite.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2024-12-10",
    fullReview: "A brilliant and darkly comedic thriller about two families from different social classes whose lives become intertwined. Parasite is a film that explores themes of class, inequality, and the dark side of capitalism. Bong Joon-ho's direction is masterful, and the film's twists and turns will keep you guessing until the very end. It's a must-see for anyone who enjoys smart and thought-provoking cinema.",
    isTopFilm: false,
  },
  {
    id: "22",
    slug: "everything-everywhere-all-at-once",
    title: "Everything Everywhere All at Once",
    year: 2022,
    genres: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    imageUrl: "/movies/everything_everywhere_all_at_once.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2025-01-17",
    fullReview: "A mind-bending and exhilarating film about a Chinese-American woman who discovers that she can access alternate realities. Everything Everywhere All at Once is a film that defies categorization, blending action, comedy, and sci-fi into a truly unique and unforgettable experience. Michelle Yeoh delivers a tour-de-force performance, and the film's visual effects are stunning. It's a must-see for anyone who enjoys innovative and boundary-pushing cinema.",
    isTopFilm: false,
  },
  {
    id: "23",
    slug: "oppenheimer",
    title: "Oppenheimer",
    year: 2023,
    genres: ["Biography", "Drama", "History", "Thriller"],
    imageUrl: "/movies/oppenheimer.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2025-02-24",
    fullReview: "A gripping and thought-provoking biographical thriller about J. Robert Oppenheimer, the theoretical physicist known as the 'father of the atomic bomb.'  Oppenheimer delves into the complex moral dilemmas faced by the scientists involved in the Manhattan Project, exploring the consequences of their creation and the weight of responsibility.  Cillian Murphy delivers a powerful and nuanced performance as Oppenheimer, capturing the character's brilliance, ambition, and inner turmoil.  Christopher Nolan's direction is masterful, creating a tense and atmospheric film that keeps you on the edge of your seat.  The film's exploration of scientific ethics, political intrigue, and the human cost of war makes it a timely and relevant masterpiece.",
    isTopFilm: false,
  },
  {
    id: "24",
    slug: "killers-of-the-flower-moon",
    title: "Killers of the Flower Moon",
    year: 2023,
    genres: ["Crime", "Drama", "History", "Thriller", "Western"],
    imageUrl: "/movies/killers_of_the_flower_moon.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-03-03",
    fullReview: "A sprawling and meticulously crafted historical crime drama that tells the true story of the Osage Nation murders in the 1920s. Killers of the Flower Moon exposes a dark chapter in American history, revealing the greed and corruption that led to the systematic exploitation and murder of Osage people for their oil wealth. Leonardo DiCaprio delivers a compelling performance as Ernest Burkhart, a man caught between his love for an Osage woman and his involvement in the criminal conspiracy. Robert De Niro shines as his manipulative uncle, William Hale. Martin Scorsese's direction is masterful, capturing the vastness of the Oklahoma landscape and the complex relationships between the characters. The film's exploration of racial injustice, systemic corruption, and the enduring legacy of historical trauma makes it a powerful and important work.",
    isTopFilm: false,
  },
  {
    id: "25",
    slug: "past-lives",
    title: "Past Lives",
    year: 2023,
    genres: ["Drama", "Romance"],
    imageUrl: "/movies/past_lives.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-03-10",
    fullReview: "A poignant and emotionally resonant drama that explores the complexities of love, fate, and the paths not taken. Past Lives tells the story of two childhood sweethearts who reconnect years later and grapple with the lingering feelings and what-ifs of their past. Greta Lee and Teo Yoo deliver captivating performances, conveying the unspoken emotions and subtle nuances of their characters' relationship. Celine Song's directorial debut is masterful, creating a film that is both intimate and universal in its exploration of human connection. The film's thoughtful exploration of cultural identity, the immigrant experience, and the ephemeral nature of time makes it a truly moving and unforgettable experience.",
    isTopFilm: false,
  },
  {
    id: "26",
    slug: "spider-man-into-the-spider-verse",
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    genres: ["Animation", "Action", "Adventure", "Comedy", "Family", "Sci-Fi", "Superhero"],
    imageUrl: "/movies/spider_man_into_the_spider_verse.jpg?height=450&width=300",
    rating: 5,
    reviewDate: "2025-03-17",
    fullReview: "A visually stunning and innovative animated film that introduces Miles Morales as Spider-Man. Spider-Man: Into the Spider-Verse breaks new ground with its unique animation style, blending comic book aesthetics with cutting-edge technology. The film's diverse cast of characters, each with their own distinct Spider-Man persona, creates a rich and engaging narrative. The story is both funny and heartwarming, exploring themes of family, responsibility, and what it means to be a hero. It's a must-see for fans of animation, superhero movies, and anyone who appreciates creative and imaginative storytelling.",
    isTopFilm: false,
  },
  {
      id: "27",
      slug: "turning-red",
      title: "Turning Red",
      year: 2022,
      genres: ["Animation", "Adventure", "Comedy", "Family", "Fantasy"],
      imageUrl: "/movies/turning_red.jpg?height=450&width=300",
      rating: 4,
      reviewDate: "2025-06-16",
      fullReview: "A charming and heartwarming animated film about a teenage girl who discovers that she turns into a giant red panda when she experiences strong emotions. Turning Red is a coming-of-age story that explores themes of family, friendship, and embracing your true self. Rosalie Chiang delivers a delightful voice performance as the main character, and Domee Shi's direction is both funny and touching. The film's vibrant animation and relatable characters make it a must-see for families and anyone who appreciates Pixar's unique brand of storytelling.",
      isTopFilm: false,
    },
  {
    id: "28",
    slug: "the-whale",
    title: "The Whale",
    year: 2022,
    genres: ["Drama"],
    imageUrl: "/movies/the_whale.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-03-31",
    fullReview: "A powerful and emotionally charged drama about a reclusive English teacher struggling with obesity and grief. The Whale features a transformative performance by Brendan Fraser, who delivers a nuanced and compassionate portrayal of a man grappling with his past and seeking redemption. The film explores themes of body image, family, and the search for connection. While some may find the film's setting claustrophobic, its intimate character study and powerful performances make it a compelling and thought-provoking experience.",
    isTopFilm: false,
  },
  {
    id: "29",
    slug: "RRR",
    title: "RRR",
    year: 2022,
    genres: ["Action", "Drama"],
    imageUrl: "/movies/rrr.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-04-07",
    fullReview: "A high-octane and visually spectacular action epic from India. RRR tells the fictional story of two revolutionaries who fight against British colonial rule. The film is a feast for the eyes, with breathtaking action sequences, vibrant costumes, and infectious musical numbers.  N.T. Rama Rao Jr. and Ram Charan deliver charismatic performances, embodying the film's themes of friendship, loyalty, and patriotism. While the plot may be over-the-top at times, its sheer energy and entertainment value are undeniable.  It's a must-see for fans of action movies and Bollywood cinema.",
    isTopFilm: false,
  },
  {
    id: "30",
    slug: "the-banshees-of-inisherin",
    title: "The Banshees of Inisherin",
    year: 2022,
    genres: ["Comedy", "Drama"],
    imageUrl: "/movies/the_banshees_of_inisherin.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-04-14",
    fullReview: "A darkly comedic and poignant drama about two friends whose relationship abruptly ends, leading to unexpected consequences. The Banshees of Inisherin features brilliant performances from Colin Farrell and Brendan Gleeson, who capture the complexities of their characters' fractured friendship. Martin McDonagh's direction is sharp and witty, creating a film that is both funny and melancholic. The film's exploration of loneliness, pride, and the fragility of human connection makes it a thought-provoking and memorable experience.",
    isTopFilm: false,
  },
  {
    id: "31",
    slug: "tar",
    title: "Tár",
    year: 2022,
    genres: ["Drama", "Music"],
    imageUrl: "/movies/tar.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-04-21",
    fullReview: "A captivating and complex drama about a world-renowned conductor whose career and personal life begin to unravel. Tár features a tour-de-force performance by Cate Blanchett, who embodies the character's brilliance, ambition, and flaws with captivating nuance. Todd Field's direction is masterful, creating a film that is both intellectually stimulating and emotionally resonant. The film's exploration of power, gender, and the complexities of the classical music world makes it a thought-provoking and timely work.",
    isTopFilm: false,
  },
  {
    id: "32",
    slug: "avatar-the-way-of-water",
    title: "Avatar: The Way of Water",
    year: 2022,
    genres: ["Action", "Adventure", "Fantasy", "Sci-Fi", "Thriller"],
    imageUrl: "/movies/avatar_the_way_of_water.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-04-28",
    fullReview: "A visually stunning and immersive sequel to James Cameron's Avatar. Avatar: The Way of Water returns to the breathtaking world of Pandora, introducing new characters and exploring the underwater ecosystems of the planet. The film's visual effects are groundbreaking, creating a truly immersive cinematic experience. While the plot may be somewhat predictable, the film's environmental themes and stunning visuals make it a worthwhile watch. It's a must-see for fans of the original Avatar and anyone who appreciates big-budget spectacle.",
    isTopFilm: false,
  },
  {
    id: "33",
    slug: "the-fabelmans",
    title: "The Fabelmans",
    year: 2022,
    genres: ["Drama"],
    imageUrl: "/movies/the_fabelmans.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-05-05",
    fullReview: "A semi-autobiographical coming-of-age story inspired by Steven Spielberg's own childhood. The Fabelmans tells the story of a young boy with a passion for filmmaking who navigates family dynamics, artistic aspirations, and the magic of cinema.  The film is a heartfelt and nostalgic look at Spielberg's early years, exploring the influences that shaped his love of movies.  Gabriel LaBelle delivers a charming performance as young Sammy Fabelman, and the supporting cast, including Michelle Williams and Paul Dano, is excellent.  While the film may be sentimental at times, its sincerity and passion for filmmaking make it a moving and enjoyable experience. It's a must-see for film buffs and fans of Spielberg's work.",
    isTopFilm: false,
  },
  {
    id: "34",
    slug: "women-talking",
    title: "Women Talking",
    year: 2022,
    genres: ["Drama"],
    imageUrl: "/movies/women_talking.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-05-12",
    fullReview: "A powerful and thought-provoking drama based on true events, about a group of Mennonite women who gather to discuss their future after discovering they have been systematically drugged and assaulted by men in their community. Women Talking is a film that tackles difficult themes of sexual violence, faith, and forgiveness. The ensemble cast delivers powerful performances, conveying the women's anger, fear, and resilience. Sarah Polley's direction is sensitive and nuanced, creating a film that is both emotionally impactful and intellectually stimulating. It's a must-see for anyone interested in social justice issues and films that challenge the status quo.",
    isTopFilm: false,
  },
  {
    id: "35",
    slug: "the-menu",
    title: "The Menu",
    year: 2022,
    genres: ["Comedy", "Horror", "Thriller"],
    imageUrl: "/movies/the_menu.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-05-19",
    fullReview: "A darkly comedic and suspenseful thriller set in the world of haute cuisine. The Menu follows a young couple who attend an exclusive tasting menu at a remote island restaurant, only to discover that the chef has some very unusual plans for the evening. Anya Taylor-Joy and Nicholas Hoult deliver strong performances, and Ralph Fiennes is chilling as the enigmatic chef. The film is a satire of the ultra-wealthy and the fine dining industry, with plenty of twists and turns to keep you guessing. It's a must-see for anyone who enjoys dark humor and suspenseful thrillers.",
    isTopFilm: false,
  },
  {
    id: "36",
    slug: "nope",
    title: "Nope",
    year: 2022,
    genres: ["Horror", "Mystery", "Sci-Fi", "Thriller"],
    imageUrl: "/movies/nope.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-05-26",
    fullReview: "A mysterious and atmospheric horror film about a brother and sister who run a horse ranch in California and encounter a strange phenomenon in the sky. Nope is a film that will keep you on the edge of your seat, with suspenseful moments and stunning visuals. Daniel Kaluuya and Keke Palmer deliver strong performances, and Jordan Peele's direction is masterful. The film explores themes of spectacle, exploitation, and the human desire to capture the impossible. It's a must-see for fans of horror and science fiction films that challenge expectations.",
    isTopFilm: false,
  },
  {
    id: "37",
    slug: "aftersun",
    title: "Aftersun",
    year: 2022,
    genres: ["Drama"],
    imageUrl: "/movies/aftersun.jpg?height=450&width=300",
    rating: 4,
    reviewDate: "2025-06-02",
    fullReview: "A poignant and melancholic drama about a father and daughter's holiday in Turkey. Aftersun is a film that explores the complexities of their relationship, with subtle hints of underlying tensions and unspoken emotions. Paul Mescal delivers a nuanced performance as the father, and newcomer Frankie Corio is captivating as the daughter. Charlotte Wells' direction is sensitive and understated, creating a film that is both intimate and emotionally resonant. The film's ambiguous ending and its exploration of memory and nostalgia make it a memorable and thought-provoking experience.",
    isTopFilm: false,
  },
    {
      id: "38",
      slug: "the-batman",
      title: "The Batman",
      year: 2022,
      genres: ["Action", "Crime", "Drama", "Thriller"],
      imageUrl: "/movies/the_batman.jpg?height=450&width=300",
      rating: 4,
      reviewDate: "2025-06-09",
      fullReview: "A dark and gritty take on the Batman story, exploring the early years of Bruce Wayne's crime-fighting career. The Batman is a visually stunning film with a compelling mystery at its core. Robert Pattinson delivers a brooding and intense performance as Batman, and the supporting cast, including Zoë Kravitz and Colin Farrell, is excellent. Matt Reeves' direction is atmospheric and suspenseful, creating a film that is both thrilling and thought-provoking. It's a must-see for fans of superhero movies and anyone who appreciates a darker and more realistic take on the genre.",
      isTopFilm: false,
    },

]

export const genres = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Family",
  "Fantasy",
  "History",
  "Horror",
  "Music",
  "Mystery",
  "Romance",
  "Science Fiction",
  "TV Movie",
  "Thriller",
  "War",
  "Western",
]

export const getRecentReviews = (count: number): Review[] => {
  return [...reviews]
    .sort((a, b) => new Date(b.reviewDate).getTime() - new Date(a.reviewDate).getTime())
    .slice(0, count)
}

export const getTopFilms = (): Review[] => {
  return reviews.filter((review) => review.isTopFilm)
}

export const movieLists: MovieList[] = [
  {
    id: "1",
    slug: "mind-bending-sci-fi",
    title: "Mind-Bending Sci-Fi",
    description: "Films that will make you question reality.",
    movies: [
      { reviewId: "6", notes: "A classic of the genre." },
      { reviewId: "15", notes: "Chilling and thought-provoking." },
      { reviewId: "19", notes: "Visually stunning and action-packed." },
      { reviewId: "22", notes: "A wild ride through the multiverse." },
      { reviewId: "27", notes: "Everything you could ever want in a movie." },
      { reviewId: "36", notes: "What is real?" },
      { reviewId: "32", notes: "Back to Pandora." },
    ],
    createdAt: "2024-03-01",
    updatedAt: "2024-03-15",
  },
  {
    id: "2",
    slug: "best-of-the-2000s",
    title: "Best Films of the 2000s",
    description: "A look back at some of the best movies from the 2000s.",
    movies: [
      { reviewId: "14", notes: "A modern classic." },
      { reviewId: "15", notes: "A chilling masterpiece." },
      { reviewId: "16", notes: "A powerful character study." },
      { reviewId: "17", notes: "So relevant today." },
      { reviewId: "11", notes: "A brutal look at war." },
      { reviewId: "12", notes: "Epic in scope." },
      { reviewId: "13", notes: "The beginning of an epic journey." },
    ],
    createdAt: "2024-04-01",
    updatedAt: "2024-04-15",
  },
  {
    id: "3",
    slug: "oscar-winners",
    title: "Oscar-Winning Films",
    description: "A selection of films that have won the Academy Award for Best Picture.",
    movies: [
      { reviewId: "1", notes: "A timeless classic." },
      { reviewId: "3", notes: "An offer you can't refuse." },
      { reviewId: "8", notes: "A powerful and important film." },
      { reviewId: "11", notes: "A realistic depiction of war." },
      { reviewId: "14", notes: "A gripping crime thriller." },
      { reviewId: "20", notes: "A beautiful and moving coming-of-age story." },
      { reviewId: "21", notes: "A brilliant social satire." },
    ],
    createdAt: "2024-05-01",
    updatedAt: "2024-05-15",
  },
  {
    id: "4",
    slug: "classic-dramas",
    title: "Classic Dramas",
    description: "Timeless dramatic films that have stood the test of time.",
    movies: [
      { reviewId: "1", notes: "A powerful story of hope and perseverance" },
      { reviewId: "3", notes: "An offer you can't refuse" },
    ],
    createdAt: "2023-10-01",
    updatedAt: "2024-02-15",
  },
]

export const getReviewById = (id: string): Review | undefined => {
  return reviews.find((review) => review.id === id)
}

export const getListById = (id: string): MovieList | undefined => {
  return movieLists.find((list) => list.id === id)
}

